services:
  app:
    build: .
    container_name: challenge-app
    image: challenge-app
    restart: unless-stopped
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    depends_on:
      - database
  
  database:
    image: postgres:alpine
    container_name: challenge-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ignitenode03

    